default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_development
  username: welob
  password: welob
  host: localhost
  port: 5432

test:
  <<: *default
  database: todo_test

# production:
#   <<: *default
#   database: todo_production
#   username: todo
#   password: <%= ENV['TODO_DATABASE_PASSWORD'] %>
