default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  port: <%= ENV.fetch('DATABASE_PORT') %>

development:
  <<: *default
  database: <%= ENV.fetch('DEVELOPMENT_DATABASE_NAME') %>

test:
  <<: *default
  database: <%= ENV.fetch('TEST_DATABASE_NAME') %>

# production:
#   <<: *default
#   database: todo_production
#   username: todo
#   password: <%= ENV['TODO_DATABASE_PASSWORD'] %>
